# Generated by Django 4.2.1 on 2023-06-12 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book.', max_length=70)),
                ('publication_date', models.DateField(verbose_name='Date the book was published.')),
                ('book_image', models.ImageField(upload_to='', verbose_name='Cover Image of the book')),
                ('description', models.TextField(max_length=1000, verbose_name='Description of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PRE-SCHOOL', 'Pre-School'), ('PRIMARY SCHOOL', 'Primary School'), ('HIGH SCHOOL', 'High School'), ('EXAM & STUDY', 'Exam & Study'), ('STORY BOOKS', 'Story Books')], max_length=20, verbose_name='Category the book falls under according to Learnrite')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text="The contributor's first name or names.", max_length=50)),
                ('last_names', models.CharField(help_text="The contributor's last name or names. ", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KINDERGARTEN I', 'Kindergarten I'), ('KINDERGARTEN II', 'Kindergarten II'), ('NURSERY I', 'Nursery I'), ('NURSERY II', 'Nursery II'), ('NURSERY III', 'Nursery III'), ('PRIMARY I', 'Primary I'), ('PRIMARY II', 'Primary II'), ('PRIMARY III', 'Primary III'), ('PRIMARY IV', 'Primary IV'), ('PRIMARY V', 'Primary V'), ('PRIMARY VI', 'Primary VI'), ('JUNIOR SECONDARY I', 'Junior Secondary I'), ('JUNIOR SECONDARY II', 'Junior Secondary II'), ('JUNIOR SECONDARY III', 'Junior Secondary III'), ('SENIOR SECONDARY I', 'Senior Secondary I'), ('SENIOR SECONDARY II', 'Senior Secondary II'), ('SENIOR SECONDARY III', 'Senior Secondary III'), ('COMMON ENTRANCE PAST QUESTIONS', 'Common Entrance Past Questions'), ('JUNIOR WAEC & NECO PAST QUESTIONS AND STUDY GUIDE', 'Junior WAEC & NECO Past Questions And Study Guide'), ('SENIOR WAEC & NECO PAST QUESTIONS AND STUDY GUIDE', 'Senior WAEC & NECO Past Questions And Study Guide'), ('FICTION', 'Fiction'), ('NON-FICTION', 'Non-Fiction'), ('ADVENTURE', 'Adventure'), ('BEDTIME STORIES', 'Bedtime Stories'), ('PICTUREBOOKS', 'Picturebooks')], max_length=50, verbose_name='Subcategories of Category Field')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The review text.')),
                ('rating', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='The ratings the reviewer has given')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time the review was created')),
                ('date_edited', models.DateTimeField(help_text='The date and time the review was last edited.', null=True)),
                ('book', models.ForeignKey(help_text='The book that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co-Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role the contributor had in the book.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='store.BookContributor', to='store.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.subcategory'),
        ),
    ]
