# Generated by Django 4.2.1 on 2023-06-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_category_contributor_subcategory_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='Book_Covers', verbose_name='Cover Image of the book'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(blank=True, help_text="The Publisher's email address.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, help_text="The Publisher's website.", null=True),
        ),
    ]
