# Generated by Django 4.2.1 on 2023-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_book_image_alter_publisher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontributor',
            name='description',
            field=models.TextField(blank=True, help_text='Information about contributor.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(help_text='Date the book was published.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('PRE-SCHOOL', 'Pre-School'), ('PRIMARY SCHOOL', 'Primary School'), ('HIGH SCHOOL', 'High School'), ('EXAM & STUDY', 'Exam & Study'), ('STORY BOOKS', 'Story Books')], help_text='Category the book falls under according to Learnrite', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(choices=[('KINDERGARTEN I', 'Kindergarten I'), ('KINDERGARTEN II', 'Kindergarten II'), ('NURSERY I', 'Nursery I'), ('NURSERY II', 'Nursery II'), ('NURSERY III', 'Nursery III'), ('PRIMARY I', 'Primary I'), ('PRIMARY II', 'Primary II'), ('PRIMARY III', 'Primary III'), ('PRIMARY IV', 'Primary IV'), ('PRIMARY V', 'Primary V'), ('PRIMARY VI', 'Primary VI'), ('JUNIOR SECONDARY I', 'Junior Secondary I'), ('JUNIOR SECONDARY II', 'Junior Secondary II'), ('JUNIOR SECONDARY III', 'Junior Secondary III'), ('SENIOR SECONDARY I', 'Senior Secondary I'), ('SENIOR SECONDARY II', 'Senior Secondary II'), ('SENIOR SECONDARY III', 'Senior Secondary III'), ('COMMON ENTRANCE PAST QUESTIONS', 'Common Entrance Past Questions'), ('JUNIOR WAEC & NECO PAST QUESTIONS AND STUDY GUIDE', 'Junior WAEC & NECO Past Questions And Study Guide'), ('SENIOR WAEC & NECO PAST QUESTIONS AND STUDY GUIDE', 'Senior WAEC & NECO Past Questions And Study Guide'), ('FICTION', 'Fiction'), ('NON-FICTION', 'Non-Fiction'), ('ADVENTURE', 'Adventure'), ('BEDTIME STORIES', 'Bedtime Stories'), ('PICTUREBOOKS', 'Picturebooks')], help_text='Subcategories of Category Field', max_length=50),
        ),
    ]
