# Generated by Django 4.2.1 on 2023-06-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bookcontributor_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcontributor',
            name='description',
        ),
        migrations.AddField(
            model_name='contributor',
            name='description',
            field=models.TextField(blank=True, help_text='Information about contributor.', max_length=1000, null=True),
        ),
    ]
