# Generated by Django 4.2.1 on 2023-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_bookcontributor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='description',
            field=models.TextField(blank=True, help_text='Information about contributor.', max_length=1500, null=True),
        ),
    ]
