# Generated by Django 4.2.1 on 2023-06-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_contributor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='image',
            field=models.ImageField(default='store/placeholder.png', help_text='Image of the contributor', upload_to='Contributor_Images'),
        ),
    ]
