# Generated by Django 4.2.3 on 2026-09-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_contributor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('SCHOOL', 'School')], max_length=20)),
                ('location', models.CharField(choices=[('LAGOS', 'Lagos'), ('OUTSIDE_LAGOS', 'Outside Lagos')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank until real pricing is supplied.', max_digits=10, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='store.book')),
            ],
            options={
                'verbose_name_plural': 'Book Prices',
                'unique_together': {('book', 'account_type', 'location')},
            },
        ),
    ]
