# Generated by Django 4.2.3 on 2026-09-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_backfill_bookprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprice',
            name='account_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('SCHOOL', 'Institution')], max_length=20),
        ),
    ]
