# Generated by Django 4.2.3 on 2026-09-11 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_seed_institution_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, help_text='The review text (optional).'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('book', 'creator')},
        ),
    ]
