# Generated by Django 4.2.3 on 2026-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_review_content_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this book from the site without deleting it.'),
        ),
    ]
