"""
Django settings for learnrite project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os.path

import dj_database_url
import whitenoise.middleware
from pathlib import Path
from decouple import config, Csv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())

# Production-only hardening (flagged by `manage.py check --deploy`) - gated
# on DEBUG rather than a new env var, so local http://localhost dev is
# unaffected (a Secure-flagged cookie or a forced HTTPS redirect would
# otherwise break every local test against plain http://).
# Render terminates TLS at its edge and forwards over plain HTTP internally,
# telling us the original scheme via X-Forwarded-Proto - SECURE_SSL_REDIRECT
# needs SECURE_PROXY_SSL_HEADER set correctly or it loops forever trying to
# "fix" a request Django can't see was already HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Starts conservative (1 hour) rather than the commonly-recommended 1 year -
# HSTS forces the browser to refuse plain HTTP for this domain for the
# whole duration, with no server-side way to undo it early if something's
# wrong. Raise it once the above is confirmed solid in production.
SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0


# Application definition

INSTALLED_APPS = [
    # Unfold themes the admin and must come before the admin app itself
    # (which here is StoreAdminConfig, since the site uses a custom
    # AdminSite - see learnrite/admin.py).
    'unfold',
    'unfold.contrib.forms',
    'unfold.contrib.filters',
    'store.apps_admin.StoreAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'compressor',
    'sass_processor',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'accounts',
    'orders',
    'chatbot',
    'store',
    'blog',
    'reps',
]

SITE_ID = 1

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Must run before CommonMiddleware (which reads request.urlconf for its
    # own slash-redirect resolution) and everything else downstream that
    # cares which urlconf is active for this request.
    'reps.middleware.SubdomainRoutingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'accounts.middleware.RequireAccountSetupMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Client sets these up in Google Cloud Console once the accounts app is live
# (see plan doc) - left blank until then so the site keeps working without them.
# Skip allauth's own unstyled "you're about to sign in with Google, continue?"
# confirmation page and its separate signup-confirmation form - go straight
# from the button click to Google, then straight into the site once back.
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_OAUTH_CLIENT_ID', default=''),
            'secret': config('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
    }
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# Admin theming (django-unfold). Sidebar is grouped by what staff actually
# do - orders, schools, catalogue - rather than the default alphabetical
# list of every model.
from django.templatetags.static import static
from django.urls import reverse_lazy

from store.logos import random_logo_path


def _admin_logo_path(request):
    # Unfold asks for SITE_ICON and SITE_LOGO separately - cached on the
    # request so both show the same random color on a given page load
    # instead of two different logos next to each other.
    if not hasattr(request, "_admin_logo_path"):
        request._admin_logo_path = random_logo_path()
    return request._admin_logo_path


UNFOLD = {
    "SITE_TITLE": "LearnRite Admin",
    "SITE_HEADER": "LearnRite",
    "SITE_SUBHEADER": "International Publishers",
    # A fresh random color every page load, same as the storefront and reps
    # portal (see store/context_processors.py) - the client wants genuine
    # variety, not one fixed color per area.
    "SITE_ICON": lambda request: static(_admin_logo_path(request)),
    "SITE_LOGO": lambda request: static(_admin_logo_path(request)),
    # Fixes the bulk-actions "Run" button staying hidden - see the CSS
    # file's own comment for why.
    "STYLES": [lambda request: static("admin/css/action_fix.css")],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        # The site's own accent, so admin reads as the same product.
        "primary": {
            "50": "255 240 234", "100": "255 224 212", "200": "255 193 169",
            "300": "255 160 126", "400": "254 126 82", "500": "254 93 38",
            "600": "224 74 24", "700": "186 57 16", "800": "148 44 12",
            "900": "117 35 10", "950": "64 18 5",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Orders",
                "separator": True,
                "items": [
                    {"title": "Orders", "link": reverse_lazy("admin:orders_order_changelist")},
                    {"title": "Coupons", "link": reverse_lazy("admin:orders_coupon_changelist")},
                    {"title": "Bulk discount", "link": reverse_lazy("admin:orders_bulkdiscountrule_changelist")},
                    {"title": "Payment accounts", "link": reverse_lazy("admin:orders_paymentaccount_changelist")},
                    {"title": "Carts", "link": reverse_lazy("admin:orders_cart_changelist")},
                ],
            },
            {
                "title": "Schools & customers",
                "separator": True,
                "items": [
                    {"title": "School verifications",
                     "link": reverse_lazy("admin:accounts_schoolverification_changelist")},
                    {"title": "Profiles", "link": reverse_lazy("admin:accounts_profile_changelist")},
                    {"title": "Addresses", "link": reverse_lazy("admin:accounts_address_changelist")},
                    {"title": "Users", "link": reverse_lazy("admin:auth_user_changelist")},
                ],
            },
            {
                "title": "Catalogue",
                "separator": True,
                "items": [
                    {"title": "Books", "link": reverse_lazy("admin:store_book_changelist")},
                    {"title": "Reviews", "link": reverse_lazy("admin:store_review_changelist")},
                ],
            },
            {
                "title": "Chatbot",
                "separator": True,
                "items": [
                    {"title": "Knowledge sections",
                     "link": reverse_lazy("admin:chatbot_knowledgesection_changelist")},
                ],
            },
            {
                "title": "Sales Reps",
                "separator": True,
                "items": [
                    {"title": "Sales reps", "link": reverse_lazy("admin:reps_salesrep_changelist")},
                    {"title": "Employment verifications",
                     "link": reverse_lazy("admin:reps_employmentverification_changelist")},
                    {"title": "Invoices", "link": reverse_lazy("admin:reps_invoice_changelist")},
                ],
            },
        ],
    },
}

# Bootstrap has no alert-error class - map Django's "error" level to
# alert-danger so messages.error() renders correctly in _messages.html.
from django.contrib.messages import constants as message_constants
MESSAGE_TAGS = {message_constants.ERROR: 'danger'}

ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')
CHATBOT_MODEL = config('CHATBOT_MODEL', default='claude-haiku-4-5-20251001')

ROOT_URLCONF = 'learnrite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates'),
                 os.path.join(BASE_DIR,'store/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'orders.context_processors.cart_count',\
                'store.context_processors.random_logo'\
            ],
        },
    },
]

WSGI_APPLICATION = 'learnrite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}"
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.validators.UppercaseStartValidator',
    },
    {
        'NAME': 'accounts.validators.SymbolValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
    'compressor.finders.CompressorFinder',
]

# Configure the SCSS compiler
SASS_PROCESSOR_ENABLED = True
SASS_PROCESSOR_ROOT = STATIC_ROOT
SASS_PROCESSOR_STATIC_PREFIX = STATIC_URL
SASS_PROCESSOR_INCLUDE_DIRS = [
    # Add any additional SCSS directories here
]

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (order confirmations, password resets) - provider is an env-var choice,
# not a code choice. Left blank until a provider is set up; see plan doc.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='learninsideout@yahoo.com')
