# Generated by Django 4.2.3 on 2026-09-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_update_for_pickup_and_part_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesection',
            name='section',
            field=models.CharField(choices=[('PRICING', 'Pricing & Account Types'), ('SIGNUP', 'Signing Up & Accounts'), ('SHIPPING', 'Pickup'), ('PAYMENT', 'Payment Methods'), ('RETURNS', 'Returns & Refunds'), ('CONTACT', 'Contact Info'), ('GENERAL', 'General / About')], max_length=20, unique=True),
        ),
    ]
