# Generated by Django 4.2.3 on 2026-09-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_profile'),
    ]

    operations = [
        # One-time backfill default of True: every Profile that already
        # exists either came from RegisterForm (an explicit real choice) or
        # predates this feature entirely, so neither should be forced
        # through the new interstitial. Going forward the model's real
        # default (False, see accounts/models.py) applies to new Profiles.
        migrations.AddField(
            model_name='profile',
            name='profile_confirmed',
            field=models.BooleanField(default=True, help_text='Whether the customer has explicitly chosen account_type/location (as opposed to still sitting on the signal-created defaults, e.g. right after a Google sign-up).'),
            preserve_default=False,
        ),
    ]
