# Generated by Django 4.2.3 on 2026-09-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_confirmed',
            field=models.BooleanField(default=False, help_text='Whether the customer has explicitly chosen account_type/location (as opposed to still sitting on the signal-created defaults, e.g. right after a Google sign-up).'),
        ),
    ]
