# Generated by Django 4.2.3 on 2026-09-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('SCHOOL', 'Institution')], default='INDIVIDUAL', help_text='Self-declared. No verification is performed.', max_length=20),
        ),
    ]
