# Generated by Django 4.2.3 on 2026-09-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, help_text='Optional - a nearby landmark to help with delivery.', max_length=255),
        ),
    ]
