# Generated by Django 4.2.3 on 2026-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, help_text="Required for institution accounts - the school/organization's name.", max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_confirmed',
            field=models.BooleanField(default=False, help_text='Whether the customer has explicitly chosen account_type/location (as opposed to still sitting on the signal-created defaults, e.g. right after a Google sign-up). Once set, account_type/location/organization_name are locked - a customer must email us to change them.'),
        ),
    ]
