# Generated by Django 4.2.3 on 2026-09-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Set once the customer clicks the link in their verification email. Google sign-ups are treated as already verified.'),
        ),
    ]
