# Generated by Django 4.2.3 on 2026-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_address_address_line1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('LAGOS', 'Lagos'), ('OUTSIDE_LAGOS', 'Outside Lagos')], default='LAGOS', help_text='Self-declared, used to arrange delivery.', max_length=20),
        ),
    ]
