# Generated by Django 4.2.3 on 2026-09-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.TextField()),
                ('first_time_buyer', models.BooleanField(help_text="Part A: 'First-time Buyer?' - unticked means a returning customer.")),
                ('years_as_customer', models.PositiveIntegerField(blank=True, help_text="Part A: 'Long-time Customer? How many years?' - blank for a first-time buyer.", null=True)),
                ('number_of_branches', models.PositiveIntegerField(default=1)),
                ('books_ages_2_3', models.PositiveIntegerField(default=0, verbose_name='Ages 2-3')),
                ('books_ages_3_4', models.PositiveIntegerField(default=0, verbose_name='Ages 3-4')),
                ('books_ages_4_5', models.PositiveIntegerField(default=0, verbose_name='Ages 4-5')),
                ('books_basic_1', models.PositiveIntegerField(default=0, verbose_name='Basic 1')),
                ('books_basic_2', models.PositiveIntegerField(default=0, verbose_name='Basic 2')),
                ('books_basic_3', models.PositiveIntegerField(default=0, verbose_name='Basic 3')),
                ('books_basic_4', models.PositiveIntegerField(default=0, verbose_name='Basic 4')),
                ('books_basic_5', models.PositiveIntegerField(default=0, verbose_name='Basic 5')),
                ('books_basic_6', models.PositiveIntegerField(default=0, verbose_name='Basic 6')),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_phone', models.CharField(help_text='One or more numbers.', max_length=100)),
                ('staff_name', models.CharField(max_length=150)),
                ('staff_post', models.CharField(max_length=150, verbose_name='Current post held')),
                ('passport_photo', models.BinaryField()),
                ('passport_photo_content_type', models.CharField(editable=False, max_length=50)),
                ('mandate_declaration_name', models.CharField(help_text="Part D: the name typed into 'I, ...' on the mandate declaration.", max_length=150)),
                ('mandate_agreed', models.BooleanField(default=False)),
                ('consent_declaration_name', models.CharField(help_text="Consent form: the name typed into 'I, ...' authorising the stamp.", max_length=150)),
                ('consent_agreed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Internal - why this was approved or rejected.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_verification', to='accounts.profile')),
            ],
        ),
    ]
