# Generated by Django 4.2.3 on 2026-09-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_schoolverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_sales_rep',
            field=models.BooleanField(default=False, help_text='Institution accounts only - whether this school already works with a LearnRite sales rep rather than dealing with us directly.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sales_rep_name',
            field=models.CharField(blank=True, help_text="Informational only, not linked to any sales rep account - the rep's name, if known.", max_length=150),
        ),
        migrations.AddField(
            model_name='schoolverification',
            name='school_photo',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='schoolverification',
            name='school_photo_content_type',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
