# Generated by Django 4.2.3 on 2026-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_school_photo_and_sales_rep_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('LAGOS', 'Lagos'), ('OUTSIDE_LAGOS', 'Outside Lagos')], default='LAGOS', help_text='Self-declared, for our records.', max_length=20),
        ),
    ]
