# Generated by Django 4.2.3 on 2026-09-13 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_unpublish_unpriced_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('local_government_area', models.CharField(max_length=100, verbose_name='Local Government Area')),
                ('home_address', models.TextField(verbose_name='Residential address')),
                ('phone_number', models.CharField(max_length=20)),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'National ID (NIN)'), ('VOTERS_CARD', "Voter's Card"), ('DRIVERS_LICENSE', "Driver's License"), ('PASSPORT', 'International Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('passport_photo', models.BinaryField()),
                ('passport_photo_content_type', models.CharField(editable=False, max_length=50)),
                ('bank_verification_number', models.CharField(help_text='Your 11-digit Bank Verification Number.', max_length=11, verbose_name='BVN')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=10)),
                ('bank_account_name', models.CharField(max_length=150)),
                ('next_of_kin_name', models.CharField(max_length=150)),
                ('next_of_kin_relationship', models.CharField(max_length=100)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('next_of_kin_address', models.TextField()),
                ('declaration_name', models.CharField(help_text='Typed name standing in for a signature on the indemnity declaration.', max_length=150)),
                ('agreed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Internal - why this was approved or rejected.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=reps.models._generate_invoice_number, max_length=20, unique=True)),
                ('customer_name', models.CharField(help_text='School or institution name.', max_length=200)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(default=reps.models._generate_receipt_number, max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='reps.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.book')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reps.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reps.salesrep'),
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('employer_name', models.CharField(max_length=150, verbose_name='Employer/place of work')),
                ('office_address', models.TextField()),
                ('home_address', models.TextField(verbose_name='Residential address')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship_to_applicant', models.CharField(max_length=100)),
                ('years_known', models.PositiveIntegerField(verbose_name='Number of years known')),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'National ID (NIN)'), ('VOTERS_CARD', "Voter's Card"), ('DRIVERS_LICENSE', "Driver's License"), ('PASSPORT', 'International Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('passport_photo', models.BinaryField()),
                ('passport_photo_content_type', models.CharField(editable=False, max_length=50)),
                ('declaration_name', models.CharField(help_text="Typed name standing in for a signature on the guarantor's undertaking above.", max_length=150)),
                ('agreed', models.BooleanField(default=False)),
                ('employment_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='reps.employmentverification')),
            ],
        ),
        migrations.AddField(
            model_name='employmentverification',
            name='sales_rep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_verification', to='reps.salesrep'),
        ),
    ]
