# Generated by Django 4.2.3 on 2026-09-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0004_invoice_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='location',
            field=models.CharField(choices=[('LAGOS', 'Lagos'), ('OUTSIDE_LAGOS', 'Outside Lagos')], help_text='Determines the institution price for each book.', max_length=20, verbose_name="Customer's location"),
        ),
    ]
