# Generated by Django 4.2.3 on 2026-09-13 13:14

from django.db import migrations, models
import django.db.models.deletion


def backfill_sales_rep_name(apps, schema_editor):
    # Existing invoices predate the snapshot - stamp them now while their
    # sales_rep FK is still live, so a rep deleted later doesn't leave old
    # invoices with a blank "Issued By".
    Invoice = apps.get_model('reps', 'Invoice')
    for invoice in Invoice.objects.select_related('sales_rep__user').filter(sales_rep__isnull=False):
        user = invoice.sales_rep.user
        invoice.sales_rep_name = user.get_full_name() or user.email
        invoice.save(update_fields=['sales_rep_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0005_alter_invoice_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sales_rep_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='reps.salesrep'),
        ),
        migrations.RunPython(backfill_sales_rep_name, migrations.RunPython.noop),
    ]
