# Generated by Django 4.2.3 on 2026-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0006_delete_sales_rep_archival'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_email',
            field=models.EmailField(blank=True, help_text="The school's own copy of the invoice is sent here once staff send it.", max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Automatic bulk-order discount, same rule as the main website.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(help_text='School or institution name.', max_length=200, verbose_name='School name'),
        ),
    ]
