# Generated by Django 4.2.3 on 2026-09-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0007_invoice_commission_and_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True, verbose_name='School address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_email',
            field=models.EmailField(blank=True, help_text="The school's own copy of the invoice is sent here once staff send it.", max_length=254, verbose_name='School email'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='School phone'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='location',
            field=models.CharField(choices=[('LAGOS', 'Lagos'), ('OUTSIDE_LAGOS', 'Outside Lagos')], help_text='Determines the institution price for each book.', max_length=20, verbose_name="School's location"),
        ),
    ]
