# Generated by Django 4.2.3 on 2026-09-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0008_school_wording'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
