# Generated by Django 4.2.3 on 2026-09-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_order_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_claimed_at',
            field=models.DateTimeField(blank=True, help_text="Set when the customer clicks 'I have completed payment' - a claim, not confirmed payment.", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('RECEIVED', 'Order Received'), ('PROCESSING', 'Processing'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
