# Generated by Django 4.2.3 on 2026-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remap_old_order_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Store Pickup')], default='DELIVERY', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_ready_notified_at',
            field=models.DateTimeField(blank=True, help_text="Set once the 'ready for pickup' email has been sent, so it's never sent twice.", null=True),
        ),
    ]
