# Generated by Django 4.2.3 on 2026-09-19 11:13

from django.db import migrations, models
from django.db.models import F

# Client dropped delivery and the Processing/Out for Delivery/Delivered
# statuses in favor of a payment-first pipeline - remap any order already
# sitting in one of the retired values to its closest new equivalent.
STATUS_REMAP = {
    'PROCESSING': 'RECEIVED',
    'OUT_FOR_DELIVERY': 'READY_FOR_PICKUP',
    'DELIVERED': 'PICKED_UP',
}


def remap_forward(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for old_status, new_status in STATUS_REMAP.items():
        Order.objects.filter(status=old_status).update(status=new_status)

    # amount_paid didn't exist before this migration - backfill it from
    # orders that had already progressed past "confirmed" so their balance
    # reads correctly now that it's tracked explicitly, instead of every
    # historical order looking fully unpaid.
    Order.objects.exclude(status__in=['PENDING', 'CANCELLED']).update(amount_paid=F('total'))
    # A PENDING order that already had an old-style claim in flight (before
    # amount_claimed existed) gets one now, for the full total, so staff can
    # approve it through the new action instead of losing the claim.
    Order.objects.filter(status='PENDING', payment_claimed_at__isnull=False).update(amount_claimed=F('total'))


def remap_backward(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for old_status, new_status in STATUS_REMAP.items():
        Order.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_method_order_pickup_ready_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_claimed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the customer just said they paid (full or part) - a claim, not confirmed. Cleared once staff approve it into amount_paid.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Cumulative confirmed payments - only changes via the 'Approve payment claim' admin action.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Store Pickup')], default='PICKUP', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('FULL_PAYMENT_RECEIVED', 'Full Payment Received'), ('PART_PAYMENT_RECEIVED', 'Part Payment Received'), ('RECEIVED', 'Order Received'), ('READY_FOR_PICKUP', 'Order Ready for Pick-up'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25),
        ),
        migrations.RunPython(remap_forward, remap_backward),
    ]
